### PR TITLE
Setup test environment

### PR DESCRIPTION
**Pull request by rodrigopinto**
- add karma
- setup first spec.

### CODE REVIEW

**Comment by raphamorim** [comment]
@rodrigopinto did you consider use Protactor?

Because karma is a great tool for unit testing, and Protractor is intended for end to end or integration testing. This means that small tests for the logic of your individual controllers, directives, and services should be run using Karma. 

Big tests in which you have a running instance of your entire application should be run using Protractor. Protractor is intended to run tests from a user's point of view - if your test could be written down as instructions for a human interacting with your application, it should be an end to end test written with Protractor.

We can proceed with the Karma. But what do you think?

**Comment by rodrigopinto** [comment]
@raphamorim I didn't, because I didn't mind to create an e2e tests right now, actually I thought to start testing directives and controllers unitarily. We can write e2e tests using Protactor, it's up to you, just let me know what are your plans for the lib.

In addition I'm a recent user of Angular and family, let me know the best practices. :)

**Comment by raphamorim** [comment]
I prefer to use protractor because it is the pattern of test libraries. Used and maintained by the angular. 
Can be?

**Comment by rodrigopinto** [comment]
Perfect, let's do it!

**Pull request closed without merging**
